### ISSUE TITLE
请问半夜自动签到在不想签到的群里怎么关闭

### ISSUE THREAD

**Issue by 1578339936** [kukume/qq-http-bot#3]
有一些群不能签到的，签到了就被踢

**Comment by 1578339936** [comment]
如果能出一个白名单。让插件只在白名单里面运行就好了。

**Comment by kukume** [comment]
ok

**Comment by 1578339936** [comment]
最好是所有功能局限在某几个群里，机器人管理的群种类有点多，这种针对所有群都开启的真的有点难搞，谢谢开发者这么晚还回复，辛苦了，晚安

**Comment by kukume** [comment]
就弄个功能总开关的白名单吧

**Comment by 1578339936** [comment]
再说几个问题，

第一个是换输入法之后发现有点输入法输入关键词机器人无响应，如搜狗输入法小米版。

近期登陆出现如下错误
程序出现异常了，异常信息为：syntax error, pos 1, line 1, column 2okk

**Comment by kukume** [comment]
已更新，群自动签到只有在开启插件的群才会签到

**Comment by 1578339936** [comment]
好的，辛苦了

**Comment by 1578339936** [comment]
![qq_pic_merged_1589536507242](https://user-images.githubusercontent.com/62222561/82037897-5d8ddc80-96d5-11ea-9f44-0bacfcacd023.jpg)
新的问题，机器人主人QQ已经填上，但是提示不是主人。
![2345截图20200515175743](https://user-images.githubusercontent.com/62222561/82038090-99c13d00-96d5-11ea-8fc4-8917f3040a0b.png)

**Comment by 1578339936** [comment]
删除db文件之后重载插件可以识别主人了，麻烦您了
